### ISSUE TITLE
NZ Citizenship Status binding should be Yes | No | Unknown

### ISSUE THREAD

**Issue by aegoodwin** [HL7NZ/nzbase#10]
http://build.fhir.org/ig/HL7NZ/nhi/branches/master/StructureDefinition-nz-citizenship.html and 
http://build.fhir.org/ig/HL7NZ/nzbase/ValueSet-citizenship-status.html

The value of the NZ citizenship status needs to capture whether someone is a NZ citizen, is not a NZ Citizen or if their NZ citizenship status is unknown.  The possible values are yes | no | unknown and might be better as a code rather than a codeable concept.

**Comment by davidhay25** [comment]
As far as I am aware, in general a CodeableConcept is preferred to a code as it is more flexible. There are notes from the FHIR project that may be of interest [here](https://confluence.hl7.org/pages/viewpage.action?pageId=35718826#GuidetoDesigningResources-Whatcodeddatatypeshouldbeused?)

**Comment by davidhay25** [comment]
Having said that, it's interesting to note that USCore uses a code for their [birthsex](https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-patient-definitions.html#Patient.extension:birthsex) extension, so may well be appropriate here.

**Comment by aegoodwin** [comment]
Is a ternery datatype offered to cater for the simple Yes/No/Unknown?

**Comment by davidhay25** [comment]
Well I guess you could use a binary where absense of the value can be taken to mean unknown (yes and no being explicit) - but that feels somewhat untidy. I'm not aware of a specific 'ternary' datatype.

I'm actually coming to like the code option!

**Comment by pkjordan** [comment]
In computer science, ternary is usually an operator, not a data type and, as David says, a common implementation of a 3 state variable is to use a nullable boolean. However, I do agree that a code is a better option and it's extensible.

I have this Code System in Terminz - https://standards.digital.health.nz/ns/nz-citizenship-status-code, with these 3 concepts...
CIT "NZ Citizen"
NCIT "Not a NZ Citizen"
UNK "Unknown")

Preferable to Y/N/U, I submit.

**Comment by pkjordan** [comment]
Agreed...
code data type (rather than coding or codeable concept)
concept list - yes, no, unknown
code system https://standards.digital.health.nz/ns/nz-citizenship-status-code
change title/description of the code system to NZ Citizenship Status

**Comment by davidhay25** [comment]
Done.

**Comment by pkjordan** [comment]
@aegoodwin  are you happy that the codes now in the CB version of the IG are all in lower case?  If so, could you please close this issue.

**Comment by aegoodwin** [comment]
Looks good
