### ISSUE TITLE
Terminology - Code System: Scope of Practice

### ISSUE THREAD

**Issue by pkjordan** [HL7NZ/nzbase#100]
The codesets in the FHIR IG and the NZHTS differ by a number of codes. Steph is currently seeking the 'source of truth' for this codeset. Will provide feedback once this is determined.

**Comment by daniel-thomson** [comment]
awaiting input on reconcilliation. Adding question status

**Comment by daniel-thomson** [comment]
Updated codesystem per NZHTS updated version from Steph. Updated version of CS & VS to 2.0.0
