### ISSUE TITLE
Some extensions do not have a version number recorded.

### ISSUE THREAD

**Issue by roylecj2** [HL7NZ/nzbase#106]
There is no version number against this extension.

**Comment by pkjordan** [comment]
@roylecj2  - is there any way of combining all the issues relating to extensions without versions into a single issue?

**Comment by roylecj2** [comment]
registration-status-code
registration-initial-date
practitonerRole-status-reason
practitonerRole-creator
nz-residency
nz-iwi
MaoriDescent
gender-original-text
established
educational-qualification
condition-on-practice
alias-type
additional-authorisation
acc-patient-occupation

**Comment by pkjordan** [comment]
Change these extensions to 1.0.0 .

**Comment by daniel-thomson** [comment]
done, also added to scope of practice extension, which had no version
