### ISSUE TITLE
Suggest adding heading to front page

### ISSUE THREAD

**Issue by daniel-thomson** [HL7NZ/nzbase#116]
On front page (index), the highlighted sentence looks like it's part of the macron section. Suggest adding a level 2 heading here (same level as the "New Zealand base FHIR implementation guide" heading). 
![image](https://github.com/HL7NZ/nzbase/assets/47614727/c29fe201-a031-4763-89dc-da470c992b3f)

Maybe "IG sections overview" as a heading, then the existing sentence "The following tabs are available from the navbar at the top.", then have the level 3 headings/sections below as they exist now.

**Comment by pkjordan** [comment]
Change this text to a section heading a re-order the following sections.

**Comment by daniel-thomson** [comment]
Completed
