### ISSUE TITLE
NZGeocode should allow for more than one datum

### ISSUE THREAD

**Issue by pat-ryan-health** [HL7NZ/nzbase#13]
The new Zealand standard datum is NZGD2000, however sometimes we may want to specify a a lat/long using a different co-ordinate system. E.g. google maps uses WGS84

- so we could add a datum code  to the NZGeocode  extension e.g.
 extension contains
    datumCode 0..1 
  
* extension[datumCode] ^definition = "The datum used for the lat/long"
* extension[datumCode].value[x] only CodeableConcept
* extension[datumCode].valueCodeableConcept from $datum-vs (preferred)

CodeSystem: Datum
Title: "Datum Code"
Description: "Identifies the coordinate system used to specify points on a map"

* ^url = $datum-cs

* #NZGD2000 "NZ offical datum, used by MoH address service"
* #WGS84 "global datum,  used by google maps"

**Comment by davidhay25** [comment]
We added nz geocode specifically to support the NZ datum (even though we didn't actually say what that datum was). By adding a separate datum element, that kinda changes the meaning of the extension doesn't it?

WSG84 is what the spec currently uses - eg http://hl7.org/fhir/location-definitions.html#Location.position

Is there some other datum that we would expect to need? If there were, I think I'd be in favour of another extension. In that case it might also be good to discuss the need in the zulip chat toi see if there is wider interest...

**Comment by pat-ryan-health** [comment]
the other data datum is NZGD2000

**Comment by davidhay25** [comment]
Is that different to the current NZ one? ie we have >1 NZ datum in use?

**Comment by pat-ryan-health** [comment]
no - it is the same - the current NZ datum used by eSAM. But it is not the same as the datum used by google maps, which is WGS84.
So adding the datum code allows us to identify which datum was used for the lat/long values

**Comment by davidhay25** [comment]
But the current extension is intended to use that datum (though we should
be more explicit in the description). I'm unclear why a separate element
within the extension is needed...

**Comment by davidhay25** [comment]
Just reviewing this again. If different datums are needed, then the solution would be to expand the [ValueSet](http://build.fhir.org/ig/HL7NZ/nzbase/branches/master/ValueSet-datumCode.html) - though as the binding strength is preferred, it isn't strictly necessary (though would be helpful). Should be discussed in committee

**Comment by pat-ryan-health** [comment]
I agree this can be closed, the value set https://nzhts.digital.health.nz/fhir/ValueSet/nz-datum-code has the codes we need
