### ISSUE TITLE
domicile-code should add Address  its Context  Of Use

### ISSUE THREAD

**Issue by pat-ryan-health** [HL7NZ/nzbase#16]
[HpiLocation](https://hpi-ig.hip-uat.digital.health.nz/StructureDefinition-HpiLocation.html ) used Domicile as a part of its [NzAddress ](https://hpi-ig.hip-uat.digital.health.nz/StructureDefinition-NzAddress.html ) extension. 

This causes the fhir validator to throw  a validation error 

![image](https://user-images.githubusercontent.com/89812164/177068714-06896de2-b7ba-4cc4-8a29-3febb7d3bf8b.png)

**Comment by davidhay25** [comment]
Hold on, why is this a modifier extension? It shouldn't be...

**Comment by pkjordan** [comment]
I checked the SDs in the IGs and on Terminz and IsModifier = false.

 

It would be useful to see the complete message.

 

Peter J

**Comment by pat-ryan-health** [comment]
I dont know why this a modifier extension, I will fix that

**Comment by pat-ryan-health** [comment]
Actually I don't know how to fix it. I don't know why it thinks it is is modifier extension. As Peter says,  IsModifier = false
BTW the source for thg is is here https://github.com/HL7NZ/hpi/tree/1.1-snapshot

"The modifier extension http://hl7.org.nz/fhir/StructureDefinition/domicile-code is not allowed to be used at this point (allowed = e:Patient; this element is [[Location.address, Address])"


If I add Address to Context of Use, th error goes away

**Comment by pat-ryan-health** [comment]
didn't mean to close this sorry

**Comment by davidhay25** [comment]
Address has been added to context
