### ISSUE TITLE
edi-address context of use

### ISSUE THREAD

**Issue by pat-ryan-health** [HL7NZ/nzbase#17]
edi-address context of use is restricted to ContactPoint.system, but HPILocation uses it in Location.telecom
https://hpi-ig.hip-uat.digital.health.nz/StructureDefinition-HpiLocation.html

**Comment by davidhay25** [comment]
Actually, are we still using this extension? Not changed...

**Comment by pkjordan** [comment]
Closed as agreed at WG meeting on Aug 19.
