### ISSUE TITLE
add  Patient.deceasedDateTime to context of use for information-source

### ISSUE THREAD

**Issue by pat-ryan-health** [HL7NZ/nzbase#19]
http://hl7.org.nz/fhir/StructureDefinition/information-source

 context of use is currently 
Patient.name
Patient.birthDate

NhiPatient also uses it for Patient.deceased

Here is the error message from the FHIR validator

 Error @ Patient.deceased.ofType(dateTime) (line 95, col36): The modifier extension http://hl7.org.nz/fhir/StructureDefinition/information-source is not allowed to be used at this point (allowed = e:Patient.name, e:Patient.birthDate; this element is [[Patient.deceased.ofType(dateTime), dateTime])
------------------------------------------------------------------------

**Comment by davidhay25** [comment]
Done. Note that I added it to the DateTime specifically (not the Boolean) - is this correct?

**Comment by pat-ryan-health** [comment]
No that didn't work - it seems to require
"Patient.deceased.ofType(dateTime)"
as the allowed context

**Comment by pat-ryan-health** [comment]
thanks that is working now
