### ISSUE TITLE
Check examples for DHB

### ISSUE THREAD

**Issue by jschealthnz** [HL7NZ/nzbase#27]
It looks like there are some extra example listed under Usage for the DHB extension...

http://build.fhir.org/ig/HL7NZ/nzbase/branches/master/StructureDefinition-dhb.html

**Comment by pkjordan** [comment]
John, could you please be more specific about any issue here - e.g., are the examples valid or superfluous? 
 Personally, I would be inclined to remove this whole entry as being superfluous, the example on the page itself is sufficient...
Examples for this Extension: [Patient/patient-address-building-name](http://build.fhir.org/ig/HL7NZ/nzbase/branches/master/Patient-patient-address-building-name.html), [Patient/patient-address-suburb](http://build.fhir.org/ig/HL7NZ/nzbase/branches/master/Patient-patient-address-suburb.html), [Patient/patient-dhb](http://build.fhir.org/ig/HL7NZ/nzbase/branches/master/Patient-patient-dhb.html)

**Comment by jschealthnz** [comment]
On the page, the line labeled "Examples for this Extension" includes three examples, as shown in @pkjordan comment above. The initial issue was to state that two of them appear unnecessary/inappropriate. Indeed, as @pkjordan says, the entire line could be removed.

**Comment by davidhay25** [comment]
This page is generated by the IG publisher based on the info in the IG. eg if an example instance has this extension, then it is listed here, or if a profile indicates that it uses the extension it will also appear. I'm not sure if it can be removed.
