### ISSUE TITLE
Truncate display of long value sets, e.g, Domicile codes?

### ISSUE THREAD

**Issue by jschealthnz** [HL7NZ/nzbase#28]
Should we be truncating really long value set expansions, e.g., first 100 displayed?

http://build.fhir.org/ig/HL7NZ/nzbase/branches/master/ValueSet-domicile-code.html

**Comment by davidhay25** [comment]
Not sure how to do this (if possible) - this is from the IG builder

**Comment by jschealthnz** [comment]
OK to leave as it's a IG Publisher issue.
