### ISSUE TITLE
Use of URL field in practitionerRole-creator as sort of just a label ... is this ok?

### ISSUE THREAD

**Issue by jschealthnz** [HL7NZ/nzbase#36]
In this page: http://build.fhir.org/ig/HL7NZ/nzbase/branches/master/StructureDefinition-practitionerRole-creator.html

we have the URL field set to just the strings person and organization... is that intended, and if it is, is that good practice?

**Comment by davidhay25** [comment]
This is a complex extension - the 'child' elements are intended to be a string. (There is a url for the extension as a whole)
