### ISSUE TITLE
Example page for registrationInitialDate issues

### ISSUE THREAD

**Issue by jschealthnz** [HL7NZ/nzbase#37]
http://build.fhir.org/ig/HL7NZ/nzbase/branches/master/Practitioner-practitioner-registration-initial-date.html

The example page DOES NOT display the actual registrationInitialDate although it is present in the code. And it DOES display the qualification which is also present in the code.

**Comment by davidhay25** [comment]
Same issues as noted.

**Comment by jschealthnz** [comment]
OK to close as appears to be an IG Publisher issue.
