### ISSUE TITLE
Practitioner Reg Status example text incorrect; and example on example page is incorrect.

### ISSUE THREAD

**Issue by jschealthnz** [HL7NZ/nzbase#38]
http://build.fhir.org/ig/HL7NZ/nzbase/branches/master/StructureDefinition-registration-status-code.html

The example link display text ("[**Practitioner with initial dat**e](http://build.fhir.org/ig/HL7NZ/nzbase/branches/master/Practitioner-practitioner-registration-status-code.html)) is wrong, although the link is correct.

On the example page http://build.fhir.org/ig/HL7NZ/nzbase/branches/master/Practitioner-practitioner-registration-status-code.html the reg status DOES NOT display correctly, and the qualification DOES display.

**Comment by davidhay25** [comment]
text changes. rendering issues already described.
