### ISSUE TITLE
Scope of practice example link incorrect, and the example page renders wrong

### ISSUE THREAD

**Issue by jschealthnz** [HL7NZ/nzbase#39]
http://build.fhir.org/ig/HL7NZ/nzbase/branches/master/StructureDefinition-scope-of-practice.html

The link display text under Example instances is wrong although the link is correct.

And the example page http://build.fhir.org/ig/HL7NZ/nzbase/branches/master/Practitioner-practitioner-scope-of-practice.html DOES NOT render the value of the extension but it DOES render the Qualifications which it shouldn't.

**Comment by davidhay25** [comment]
Fixed the text. Issue with extension rendering same as others. If we don't want the qualifications to appear, then the solution is to remove it from the example.
