### ISSUE TITLE
Suburb example page doesn't render the extension value

### ISSUE THREAD

**Issue by jschealthnz** [HL7NZ/nzbase#41]
http://build.fhir.org/ig/HL7NZ/nzbase/branches/master/Patient-patient-suburb.html

**Comment by davidhay25** [comment]
It is present when you look at the json. The rendered page on the front is generated by the IG builder - it is possible to modify the template used, though this is not straightforward. Is it necessary (given that the extension is present in the instance?

**Comment by jschealthnz** [comment]
After further discussion, OK to leave this as is given it's more of a IG Publisher issue.
