### ISSUE TITLE
Add Summary Text to NzAddress profile

### ISSUE THREAD

**Issue by jschealthnz** [HL7NZ/nzbase#44]
http://build.fhir.org/ig/HL7NZ/nzbase/branches/master/StructureDefinition-NzAddress.html

At a minimum, copy the description text ("Adds building name, suburb, domicile code and geocode to the Address datatype") into the right spot so that it appears in the "Summary" field in the "Text Summary" tab view.

**Comment by jschealthnz** [comment]
On further review, it appears that this needs to be done for all the profiles in the IG.

**Comment by davidhay25** [comment]
Where is the 'Text Summary' tab?

**Comment by jschealthnz** [comment]
> Where is the 'Text Summary' tab?

It's the first tab in the section "Formal Views of Profile Content" that also has the Snapshot View, Differential View, etc.

**Comment by jschealthnz** [comment]
After further discussion, we'll leave this alone as it appears to be an IG Publisher issue.
