### ISSUE TITLE
Updates to Messaging Address Extension

### ISSUE THREAD

**Issue by pkjordan** [HL7NZ/nzbase#47]
a. Refine the description (e.g. distinguish it from edi-address)
b. Add the following resources to the context of use...

- Location
- Organization
- HealthcareService
- Practitioner
- PractitionerRol

**Comment by davidhay25** [comment]
Updates context. Can you suggest appropriate wording?

**Comment by pkjordan** [comment]
I can't see the context of us updates yet - but the description now looks ok to me.

**Comment by pkjordan** [comment]
Practitioner still missing from context of use and add a comment to edi-address about recommending use of messaging-address instead.

**Comment by pkjordan** [comment]
Text added (without HTML formatting).
