### ISSUE TITLE
Entries on the Terminology Page That Need Correcting

### ISSUE THREAD

**Issue by pkjordan** [HL7NZ/nzbase#48]
ValueSet Column in the Value Sets Grid...
- Change 'Coverage Category VS' to just 'Coverage Category'
- Change 'CoverageType type VS' to ''Coverage Type'
- Change 'domicileCode' to 'Domicile Code'

Purpose Column in the Value Sets Grid...
- Change 'New Zealand codes for CoverageType types' to 'New Zealand codes for 'Coverage Types'

Canonical URL Column in Value Sets Grid...
- Coverage Category -  the correct URL is [https://nzhts.digital.health.nz/fhir/ValueSet/coverage-category-code]

CodeSystem Column in the Value Sets Grid...
- Change 'domicileCode' to 'Domicile Code'

General
- consistent use of capitals (these are effectively titles)
- is it possible to sort these grids in alphabetic order of the titles (first column)

**Comment by davidhay25** [comment]
All done...
