### ISSUE TITLE
NZ Coverage Profile - Binding to Class Type

### ISSUE THREAD

**Issue by pkjordan** [HL7NZ/nzbase#49]
This should be to https://nzhts.digital.health.nz/fhir/ValueSet/coverage-category-code

**Comment by davidhay25** [comment]
it already is? (or am I missing something)

**Comment by pkjordan** [comment]
The binding URL should resolve to a page in the IG. However, that page may not exist as the Terminology Page has an incorrect Value Set for Coverage Category. The binding strength should also be preferred and not extensible (we are trying to avoid the use of that strength in the IG as it's too confusing for implementers).

**Comment by pkjordan** [comment]
Binding strength still needs to be changed to preferred.

**Comment by pkjordan** [comment]
Cannot change binding strength of a core element in an IG, so will submit a Jira Ticket for this to be changed in R5.
