### ISSUE TITLE
Incorrect Version of Code Systems Cited on Value Set Pages

### ISSUE THREAD

**Issue by pkjordan** [HL7NZ/nzbase#58]
The expansions are all cited to be based on the current version of the IG, rather than the correct version of the relevant code system.

**Comment by pkjordan** [comment]
Fixed by David Hay during WG meeting on Aug 26.

**Comment by pat-ryan-health** [comment]
have you tried setting 
 apply-version: 'false'
in sushi-config-paarmeters
 https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
 
 - that works for us

**Comment by davidhay25** [comment]
I did - and it didn't seem to work. Can you reference the page where it
worked?

**Comment by pat-ryan-health** [comment]
this is our hip-fhir-common  where we define terminology whichh si not in nzbase:

https://common-ig.hip.digital.health.nz/site/index.html

- i tried a local build of nzbase with 
apply-version: 'false'

and it worked correctly - iwi code set showed version 2.0 - 

I am running an old version of the publisher though : Version 1.1.89  ( I haven't been a bel to get newer version to work)

**Comment by pat-ryan-health** [comment]
I also tried apply-version: false (no quotes) - that worked for me too

**Comment by pkjordan** [comment]
NZ Ethnicity Version should be 2.1.0 - not the version of the IG.
