### ISSUE TITLE
Iwi ValueSet - code and level grouped in one column.

### ISSUE THREAD

**Issue by venusinfo** [HL7NZ/nzbase#59]
http://build.fhir.org/ig/HL7NZ/nzbase/branches/master/ValueSet-iwi.html

Code and Level are in one column. Two digit codes are for geographical groping while four digit codes are actual Iwi names.

Shown here on Stats NZ - http://aria.stats.govt.nz/aria/?_ga=2.122257291.1697971450.1603248559-359906782.1603248559#ClassificationView:uri=http://stats.govt.nz/cms/ClassificationVersion/NdoVpaBrOkxg61br

Apologies in advance if I missed anything , and the issue reported is by design.

**Comment by pkjordan** [comment]
The 2 digit codes are marked as 'abstract' (i.e. non-selectable) in the expansions of this value set. Advice is being sought from Stats NZ to confirm that they are non-selectable and, if so, we should add this advice to the page in the IG.

**Comment by lawley** [comment]
This looks to me like this should be an hierarchical CodeSystem with hierarchyMeaning set to `grouped-by` (or possibly `classified-with`).
Also, there are no properties defined on the codes in the CodeSystem -- how are they being marked as abstract @pkjordan ?

**Comment by pkjordan** [comment]
@lawley  The NZ Iwi Code System is owned by Stats NZ (and used for many purposes both in and outside of healthcare) .There is no clear advice in their documentation around non-selectable codes (and, as you say, no defined code system properties), so we have proposed to HISO that, for the purposes of this IG, we might indicate that the 2 digit codes are abstract as HISO has suggested that they be excluded from the Value Set expansion in the IG which (I believe) we don't have the authority to do.  However, this may be the last version of the NZ Base IG to contain these local terminologies as (IMO) they would be better housed in an IG for the NZ Terminology Service.

**Comment by pkjordan** [comment]
Place note on the ValueSet Page to the effect that.. "The 2 digit codes are abstract codes and provided in the expansion for navigational purposes. A user should not  select an abstract code directly as a proper value."

**Comment by pkjordan** [comment]
Update made.
