### ISSUE TITLE
Add OPLS to NZ Practitioner Scope of Practice Codes

### ISSUE THREAD

**Issue by pkjordan** [HL7NZ/nzbase#60]
Description required.  @pat-ryan-health

**Comment by NicholasDom** [comment]
Hi Peter,

Sorry about the delay. Just checking out scope of practice codes and some background information
Here is a list of codes that are in our HIP common scope of practice codesystem that are not in the nzbase version and should be added please.

DEOH	Oral Health Practice
OPLS	Ophthalmic Laser Surgeries
OPPO	Provisional Optometrist
OSED	Osteopath - Educator
OSGE	Osteopath - Gerontology
OSPM	Osteopath - Pain Management
OSSP	Osteopath - Special Purpose
OSTO	Trainee Osteopath
OSVO	Visiting Osteopath Presenter
OSWA	Osteopath - Western Medical Acupuncture
OSCA	Osteopath - Child and Adolescent Health
PAPS	Paramedic
PBPS	Psychotherapist
PBCA	Psychotherapist with Child and Adolescent Specialism
PBIN	Interim Psychotherapist
PSHE	Health Psychologist
PSNE	Neuropsychologist

**Comment by pkjordan** [comment]
@NicholasDom  - thanks for that list. I've added these to the Code System instance on Terminz and will deploy that this evening. Hopefully, @davidhay25  will be able to grab that and update the IG accordingly.

**Comment by pkjordan** [comment]
Approved. David will request the complete ValueSet from Terminz and enter it into the IG.

**Comment by pkjordan** [comment]
Completed.

**Comment by NicholasDom** [comment]
Hi @pkjordan,

I noticed that this code (PSCLPSED) has been added to the scope of practice codesystem. This is an error it looks like two codes have been added together. Can it be removed please.

Error:
**PSCLPSED	https://standards.digital.health.nz/ns/practitioner-scope-of-practice-code	Clinical and Educational**

Actual codes that are in the codesystem:
PSCL https://build.fhir.org/ig/HL7NZ/nzbase//CodeSystem-scopeOfPractice.html#scopeOfPractice-PSCL)
PSED https://build.fhir.org/ig/HL7NZ/nzbase//CodeSystem-scopeOfPractice.html#scopeOfPractice-PSED)

<img width="492" alt="Scope of Practice codesystem" src="https://user-images.githubusercontent.com/101608998/189770757-d6e444e3-95b1-4e49-9c91-34387a7fa1c9.PNG">

**Comment by davidhay25** [comment]
oops - that might be me - hold on...

**Comment by davidhay25** [comment]
So have removed it from the IG (might take a few minutes for the update to
be processed)

but it's in terminz as well...

cheers

**Comment by pkjordan** [comment]
It will be removed in the next deployment of Terminz (tonight or tomorrow).

 

Peter
