### ISSUE TITLE
CodeSystems should populate the valueSet element

### ISSUE THREAD

**Issue by lawley** [HL7NZ/nzbase#61]
I believe it is good practice for CodeSystems to declare the URI of their associated "all codes" ValueSet with the `CodeSystem.valueSet` element

**Comment by pkjordan** [comment]
@lawley  - does your comment relate to the fact that this URI (the FHIR spec states that is should be a 'canonical reference') is not cited in the IG itself? I've actually populated this element in the instances of these CodeSystems on Terminz (with nzhts uris) - but IMO the source of truth should be the NZHTS IG and NZ Base should point to that. It is an optional element, but agree that it's good practice to populate it - certainly for the code systems which are too large to return in a a single ValueSet and the implicit ValueSet syntax comes into play.

**Comment by pkjordan** [comment]
ValueSet URIs in the IG all return the entire code system (if no additional filters are provided) as these have a relatively small number of concepts. WG felt this was sufficient until the NZCTS is available.
