### ISSUE TITLE
CodeSystem: Coverage type to contain a code for Health Insurance

### ISSUE THREAD

**Issue by pkoval21** [HL7NZ/nzbase#62]
Thanks for creating the Coverage profile to use for NZ use cases to capture patients CSC Card, HUHC Card & GMS details.
ALEX will be using these in our next release coming out in end of September 2022.

Just wanted to check if a new code can be introduced for Health Insurance, this will allow us to use this for Health Insurance schemes a patient has like Southern Cross etc.

If a new code for Health Insurance cannot be added to the https://standards.digital.health.nz/ns/coverage-type-code

Then we would have to use the below-

"type" : {
    "coding" : [
      {
        "system" : "http://terminology.hl7.org/CodeSystem/v3-ActCode",
        "code" : "HIP",
        "display" : "health insurance plan policy"
      }
    ]
  },

**Comment by pkjordan** [comment]
Health Insurance Plan Policy is really implicit in the use of the resource, so if it's not something really NZ-specific like CSC, HUHC or GMS, I'd be included not to use Coverage Type and rely on using the Policy Holder element. However, we might discuss this for the next version so maybe you could hold off using that HL7 v3 Act Code for the type as it's not a mandatory element.

**Comment by pkoval21** [comment]
Thanks for your comments Peter, we will use Policy Holder and Payor elements to denote the Health Insurance vendor and would wait for a NZ specific Coverage Type in the next version.
