### ISSUE TITLE
CodeSystem: Level 4 ethnicity codes

### ISSUE THREAD

**Issue by NicholasDom** [HL7NZ/nzbase#63]
Hi,

I have just noticed a discrepancy between NZ base Level 4 ethnicity codes Version: 2.1.0 and the Stats NZ Ethnicity New Zealand Standard Classification 2005 V2.1.0.

This is creating validator issues in the NHI.
See below for an example of the differences. It won't let me attach an excel spreadsheet

I have reached out to Steph in HISO for comment

<img width="543" alt="Ethnicity differences screenshot" src="https://user-images.githubusercontent.com/101608998/189815140-a2b6c951-47d8-4de2-8c59-b2572938eb88.PNG">

**Comment by pkjordan** [comment]
Apologies, I relied on the diff report from v1 and this obviously wasn't comprehensive enough!

I'll correct these and put them up on Terminz later this evening. @davidhay25 will you be able to pick them up from Terminz and put them in the IG in the next day or so?
Update - the corrected Code System and Value Set resources are now up on Terminz.

**Comment by davidhay25** [comment]
Sure - just let me know when ready...

cheers

**Comment by pkjordan** [comment]
Completed by David Hay on 13th Sept.

**Comment by NicholasDom** [comment]
Kia ora,

I just had a quick look at the ethnicity code system https://build.fhir.org/ig/HL7NZ/nzbase//CodeSystem-ethnicityL4.html<https://build.fhir.org/ig/HL7NZ/nzbase/CodeSystem-ethnicityL4.html>
Looks like it is still showing the old values?

Thanks,
Nick


Ngā mihi nui
Nicholas Dominick
Kaiātiri Pakihi (Business analyst)
Data and Digital
īmēra: ***@***.******@***.***>
133 Molesworth Street, Wellington

***@***.***

Te Whatu Ora – Health New Zealand
TeWhatuOra.govt.nz

**Comment by pkjordan** [comment]
@NicholasDom are you sure - these look like the current values, from v2.1.0, to me?

**Comment by NicholasDom** [comment]
Apologies @pkjordan I think I looked at the release IG the other day instead of the build, ended up in a right mess looking at old codesystems.
