### ISSUE TITLE
CodeSystem: Information Source

### ISSUE THREAD

**Issue by NicholasDom** [HL7NZ/nzbase#64]
What: Update PPRT definition to "passport".

Why: Current definition "An overseas passport is acceptable" - does not apply to NZ citizenship status.

Rationale: HISO has different descriptions for codes depending on the use of the information source.
https://build.fhir.org/ig/HL7NZ/nzbase/branches/master/CodeSystem-information-source.html currently has one definition for the code for multiple scenarios

E.g. From HISO
Code      Display                             Description                                                       Used to confirm:**
BRCT      Birth certification             An overseas birth certificate                             Name and Date of birth
BRCT      NZ Birth certificate                                                                                    NZ Citizen Status
PPRT      Passport                           Does not state overseas or NZ passport          Name, Date of birth, Country of birth, Residency status
PPRT      NZ Passport                                                                                               NZ Citizenship status

*I haven't had a chance to cross check the rest of the codes.

**Comment by NicholasDom** [comment]
[hiso-10046-2022 information source.xlsx](https://github.com/HL7NZ/nzbase/files/9595945/hiso-10046-2022.information.source.xlsx)

**Comment by pkjordan** [comment]
@davidhay25 - the only change that needs to be made is to change the text in the Definition Column of the PPRT code to 'passport'.

**Comment by pkjordan** [comment]
Change implemented.
