### ISSUE TITLE
ValueSet: District Health Board Identifer - incorrect display names

### ISSUE THREAD

**Issue by NicholasDom** [HL7NZ/nzbase#65]
Hi,

Our validator just picked up this issue for DHB display names from this value set http://build.fhir.org/ig/HL7NZ/nzbase/branches/master//ValueSet-dhb.html

See MoH website for list of correct display names https://www.health.govt.nz/nz-health-statistics/data-references/code-tables/common-code-tables/district-health-board-code-table

Note: We have the correct set in HIP Common but have included the Maori macrons if that is possible https://common-ig.hip.digital.health.nz/site/ValueSet-dhb-1.0.html

**Comment by pkjordan** [comment]
There are 3 alternative versions of the display names for District Health Boards...
a. The list displayed on the Ministry of Health Web Site
b. The list in the Excel spreadsheet that can be downloaded from the Ministry of Health Web Site (upper case versions of a.)
c. The HPI Organisational List that forms part of the monthly HPI distribution (the NZ Base IG uses this)
Can we please have a clear indication from the HPI-O Code System Owner as to what are the correct designations.

**Comment by NicholasDom** [comment]
Thanks for the comments above Peter.
 
I had a discussion and the multiple names are due to legal names vs indicative names. A bit of an interesting space going forward with the move from DHBs to districts. Let's leave this for now and pick it up again in the future.

**Comment by pkjordan** [comment]
Agreed to close issue until correct (ex) DHB names are determined.
