### ISSUE TITLE
Domicile Codesystem is missing the 2013 codes

### ISSUE THREAD

**Issue by NicholasDom** [HL7NZ/nzbase#66]
Reconciliation of the nzbase CodeSystem: Domicile Code Version: 1.1 and the Te Whatu Ora domicile_code_table_census_v3_2013

159 new codes
48 codes with name changes

@pat-ryan-health can provide @davidhay25 with the .fsh file to save me pasting all the changes here.

**Comment by pkjordan** [comment]
@NicholasDom @davidhay25  - this version is already available on Terminz - if it's easier for David to grab it from there.

**Comment by pkjordan** [comment]
@NicholasDom - could you please check the updated version to see if the codes and version align with your requirements. NB the expansion on the Value Set page does not include the 282 retired codes. Hence the number of codes listed is 2059

**Comment by NicholasDom** [comment]
Hi @pkjordan. Sorry for late reply. We still have NHI records with domicile codes that are status R and therefore not currently in the nzbase codeystem. Working towards a solution.

**Comment by pkjordan** [comment]
@NicholasDom - depends on whether you are going to validate resource instances that will contain retired domicile codes against a profile derived from NZ Base and permit or reject those retired codes.
