### ISSUE TITLE
NZ Citizenship status version change from 1.0.0 to 1.1.0

### ISSUE THREAD

**Issue by NicholasDom** [HL7NZ/nzbase#67]
NZ Citizenship status - change version 1.0.0 to 1.1.0 (valueset and codesystem)
NHI Soap api and HISO 10046 included codes N,U,Y which is version 1.0.0
Releasing a new codesystem with no, unknown and yes requires mapping between code systems and therefore a change from 1.0.0 to 1.1.0.

**Comment by pkjordan** [comment]
@davidhay25  - there is still this outstanding request from Steph...
Also, can we please change the definition in the NZ Citizenship status CodeSystem to read ‘person’ instead of ‘patient’

**Comment by pkjordan** [comment]
Fixed in 2022-10-10 version 2.1-rc2

**Comment by NicholasDom** [comment]
Thanks @pkjordan @davidhay25
