### ISSUE TITLE
NZ Residency Status version change from 1.0.0 to 1.1.0

### ISSUE THREAD

**Issue by NicholasDom** [HL7NZ/nzbase#68]
NZ Residency status - change version 1.0.0 to 1.1.0 (valueset and codesystem)
NHI legacy, HISO 10046, and nzbase 1.0.0 – Release  included codes for N,U,Y
Releasing a new codesystem with no, unknown and yes requires mapping between code systems and therefore a change from 1.0.0 to 1.1.0.

**Comment by pkjordan** [comment]
Completed by @davidhay25

**Comment by NicholasDom** [comment]
Thanks @pkjordan @davidhay25
