### ISSUE TITLE
Improve Description of Value Sets and Code Systems On Section 1.2 of the Home Page

### ISSUE THREAD

**Issue by pkjordan** [HL7NZ/nzbase#7]
**Before.**..
ValueSets are ‘selectors’ of concepts that apply to some particular coded element in an Extension Definition or Profile - they contain a list of possible values for that element. It is usually possible to use other values if needed, but these are the ‘recommended’ values. Note that it is possible to have elements where the concept MUST come from the ValueSet, though this is uncommon.
**After...**
ValueSets are sets of codes, drawn from one or more code systems, intended for use in coded data elements in Resources, as defined by a particular conformance rule - such as an Extension or Profile. The ValueSets in this Guide are 'recommended' values, but it may be possible for implementers to use additional concepts if the rules defined by a particular Extension or Profile permit this.

**Before...**
CodeSystem resources are used to define specific concepts. Generally, it is preferred to use an ‘external’ terminology like SNOMED or LOINC, but sometimes it isn’t possible to find the matching concepts there so they need to be defined separately.
**After**
CodeSystem resources are used to declare the existence of and describe a code system , its key properties, and optionally define a part or all of its content. Wherever possible, the use of international terminologies, such as SNOMED CT, is recommended; however, a number of New Zealand-specific code systems are included in this Guide to meet unique, local requirements.

**Comment by pkjordan** [comment]
FHIR IG WG feedback...
Add hyperlinks to ValueSets and CodeSystem names - plus SNOMED CT
Remove extraneous space between system and ,

**Comment by davidhay25** [comment]
Which ValueSets and CodeSystem names need hyperlinks? Have done the other ones...

**Comment by pkjordan** [comment]
Which version of the IG should I be looking at – Ballot or CB, it it’s the later could you please send me the link.

 

Cheers,

 

Peter

**Comment by davidhay25** [comment]
The ballot version is unchanged - the one I'm updating is the build version
- http://build.fhir.org/ig/HL7NZ/nzbase/branches/master/index.html

**Comment by pkjordan** [comment]
Sorry, long day and tired – but I’m seeing the Ballot 0.9 version and all the ValueSets and CodeSystem URLs are hyperlinked to other pages in the IG.

 

Definitely missing something, please help!  😊

 

PJ

**Comment by pkjordan** [comment]
I was referring to the text of the Terminology Section in the Home Page. My proposed amendment didn’t include the hyperlinks to “CodeSystem” and “ValueSets” in the core FHIR Spec that were in the original text, but I see that they have now been in the updated version of the text in the Current Build version.
