### ISSUE TITLE
Extension - additional-authorisation description is ambiguous

### ISSUE THREAD

**Issue by roylecj2** [HL7NZ/nzbase#70]
additional-authorisation description on the main extensions page reads

_Additional authorisations that a practitioner is authorised to perform_

I am unsure what an authorisation is from the above description. Can we provide more detail on this?

**Comment by pkjordan** [comment]
Refer for updated description to @NicholasDom

**Comment by pkjordan** [comment]
This uses the HISO definition, but we may need to add some of the surrounding context.

**Comment by daniel-thomson** [comment]
Added some context + examples.
