### ISSUE TITLE
Extension - long-term-condition extension has a URL to health nz but not shown as a hyperlink

### ISSUE THREAD

**Issue by roylecj2** [HL7NZ/nzbase#75]
The URL for long term condition does not show the https://www.health, etc. It is shown in plain text, would be useful to have as a hyperlink.

**Comment by pkjordan** [comment]
Should be hyperlinked to https://www.tewhatuora.govt.nz/for-the-health-sector/health-sector-guidance/diseases-and-conditions/long-term-conditions

**Comment by daniel-thomson** [comment]
Updated to new Te Whatu Ora URL and made a hyperlink.
