### ISSUE TITLE
Educational qualification example needs correcting

### ISSUE THREAD

**Issue by aegoodwin** [HL7NZ/nzbase#8]
http://igs.clinfhir.com/ig/nzbase/StructureDefinition-educational-qualification.html

The educational qualification example in the 'Example of extension' on the extension page should be the same as what is in the 'Example instances' here
http://igs.clinfhir.com/ig/nzbase/Practitioner-practitioner-educational-qualification.xml.html
The 'Example instance' is the correct example.

**Comment by pkjordan** [comment]
Passed unanimously by the WG.
