### ISSUE TITLE
Extension - nz-iwi - RelatedPerson not included in a profile

### ISSUE THREAD

**Issue by roylecj2** [HL7NZ/nzbase#84]
iwi can be against Patient, Practitioner and RelatedPerson - but we don't have an NZRelatedPerson profile including the iwi extension - should we?

**Comment by daniel-thomson** [comment]
As per [issue 87](https://github.com/HL7NZ/nzbase/issues/84), we don't currently have a RelatedPerson profile, so we should revisit this in v4. 

Suggest tagging with version 4 & closing.
