### ISSUE TITLE
PractitionerRole status reason example should be one from the preferred codeset

### ISSUE THREAD

**Issue by aegoodwin** [HL7NZ/nzbase#9]
http://igs.clinfhir.com/ig/nzbase/StructureDefinition-practitionerRole-status-reason.html

The 'Example of extension', and the 'example instances' for practitionerRole status reason are showing a code text value="Practitioner has resigned" that is not part of the preferred valueset.

http://igs.clinfhir.com/ig/nzbase/ValueSet-hpi-practitionerrole-status-reason.html

**Comment by pkjordan** [comment]
WG voted unanimously in favor
