### ISSUE TITLE
Terminology - Code System: Type of alias

### ISSUE THREAD

**Issue by pkjordan** [HL7NZ/nzbase#95]
Check the 'Display' of the code 'Current'

**Comment by daniel-thomson** [comment]
The display of this code is quite long - I suspect it may be intended, but doesn't fit with the rest of the single / short display values. Current display value is:  
| code | display | definition | 
| --- |  ---  |  --- |
| current |  Current unverified or unofficial name | The name currently used for a facility. |

Will check with the HIP team. Link to current expansion: https://build.fhir.org/ig/HL7NZ/nzbase/ValueSet-location-alias-type.html#expansion

**Comment by daniel-thomson** [comment]
Display changed to 'Current' per hip team advice.
